name: Commit check

on: [push]

jobs:
  files-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: test_env
          cache-environment: true
