name: Commit check

on: [push]

jobs:
  files-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: test_env
          cache-environment: true

      - name: Run all linters
        shell: bash -l -eo pipefail {0}
        run: |
          micromamba activate test_env
          pre-commit run --all-files --verbose --show-diff-on-failure
