name: Commit check

on: [push]

jobs:
  files-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Install dependencies
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: requirements.txt
          create-args: >-
            python=3.11
          cache-environment: true
      - name: Run all linters
        shell: bash -l -eo pipefail {0}
        run: |
          micromamba activate test_env
          pre-commit run --all-files --verbose --show-diff-on-failure
